### ISSUE TITLE
Adding License Information

### ISSUE THREAD

**Issue by ercanersoy** [joncampbell123/minx86dec#2]
I would like to add license information of minix86dec.

Thanks and best regards,
Ercan

**Comment by joncampbell123** [comment]
This was a fun little experiment that I threw together in two weeks sometime back in 2008, though it fell into premature optimization hell a bit. Not sure.

**Comment by ercanersoy** [comment]
I like this project. minix86dec Project is useful for emulators. It can be use by everyone. minix86dec can be licensed under MIT license.

**Comment by joncampbell123** [comment]
Works for me.
